[options]
# # addons_path = odoo\addons
# # addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
# admin_passwd = 12345
# db_host = localhost
# db_name = DocytTest
# db_password = openpgpwd
# db_port = 5432
# db_user = openpg
# xmlrpc_port = 8069
# list_db = True
# # logfile = ./var/log/odoo-server.log
# log_db = True
# log_db_level = debug
# log_handler = [':INFO']
# log_level = debug

# # Enable log rotation
# # logrotate = True
# # max_filesize = 1000000  # Size in bytes (1MB in this example)
# # logfile_rotation = 5     # Keep 5 old log files

# workers = 0

# # HTTP-related settings
# http_enable_cors = True
# http_cors = *

# # CORS headers configuration
# cors_allow_origins = http://localhost:8000
# cors_max_age = 3600
# cors_allow_methods = GET, POST, PUT, DELETE, OPTIONS
# cors_allow_headers = Origin, Content-Type, Accept, Authorization
# cors_allow_credentials = true


admin_passwd = odooadmin
db_host = docytdb-1.csu2wdvdmaco.eu-north-1.rds.amazonaws.com
db_port = 5432
db_name = odoords
db_user = docytuser
db_password = docytodoo
# addons_path = /home/ec2-user/odoo-project/odoo/addons/, /home/ec2-user/odoo-project/devops-odoo/
# logfile = /home/ec2-user/odoologs/odoo.log
logfile = /var/log/odoo/odoo.log
xmlrpc = True
xmlrpc_interface = 0.0.0.0
xmlrpc_port = 8069

# HTTP-related settings
http_enable_cors = True
http_cors = *

# CORS headers configuration
cors_allow_origins = http://localhost:8000, http://localhost:3000, http://13.60.54.33:8000
cors_max_age = 3600
cors_allow_methods = GET, POST, PUT, DELETE, OPTIONS
cors_allow_headers = Origin, Content-Type, Accept, Authorization
cors_allow_credentials = true
